swagger: '2.0'
info:
  title: DFCMS
  version: 1.0.0
host: localhost
basePath: /ords/deva/dfcmsords/web
schemes:
- http
produces:
- application/json
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication.
tags:
- name: DFCMS
- name: Health
paths:
  /caseSequenceNumber:
    get:
      tags:
      - DFCMS
      security:
      - basicAuth: []
      description: Get case sequence number
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/caseSequenceNumberResponse'
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/errorMessage'
      parameters:
      - name: driver_license_no
        in: query
        type: string
        description: Implicit parameter
      - name: surname_code
        in: query
        type: string
        description: Implicit parameter
  /health:
    get:
      tags:
        - Health
      operationId: health
      security:
      - basicAuth: []
      description: Dummy endpoint to check that API calls are working
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/healthOrdsResponse'
definitions:
  healthOrdsResponse:
    type: object
    required:
      - appid
      - method
      - status
      - host
      - instance
    properties:
      appid:
        type: string
      method:
        type: string
      status:
        type: string
      host:
        type: string
      instance:
        type: string
  caseSequenceNumberResponse:
    type: object
    required:
    - case_sequence_number
    - case_description
    - status_code
    - status_message
    properties:
      case_description:
        type: string
      case_sequence_number:
        type: string
      status_code:
        type: string
      status_message:
        type: string
  errorMessage:
    type: object
    required:
    - status_code
    - status_message
    properties:
      status_code:
        type: string
      status_message:
        type: string
