server:
  port: 8081
  servlet:
    context-path: /paymentservice
dps:
  crc:
    endpoint:
      approved: ${CRC_ENDPOINT_APPROVED}
      declined: ${CRC_ENDPOINT_DECLINED}
      error: ${CRC_ENDPOINT_ERROR}
