
version: '3.7'
services:
  
  #############################################################################################
  ###                               DPS service API                                         ###
  #############################################################################################
  service-api:
    image: nginx:latest
    volumes:
      - ./src/service-api/conf/nginx.conf:/etc/nginx/nginx.conf
      # TODO: renable sharing logs
      # - ./nginx-log:/var/log/nginx
    ports:
      - 8080:80
    networks:
      - dps-net

  #############################################################################################
  ###                  DPS service API SPLUNK UNIVERSAL FORWARDER                           ###
  #############################################################################################
  service-api-universalforwarder:
    image: splunk/universalforwarder:7.3.2
    volumes:
      - ./.splunk/conf/inputs.conf:/opt/splunkforwarder/etc/system/local/inputs.conf
      - ./.splunk/conf/outputs.conf:/opt/splunkforwarder/etc/system/local/outputs.conf
      # TODO: renable sharing logs
      # - ./nginx-log:/var/log/nginx
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=$SPLUNK_PWD
    ports:
      - "8089"
      - "9997"
    networks:
      - dps-net

  #############################################################################################
  ###                               DPS payment service                                     ###
  #############################################################################################
  payment-service:
    build:
      context: ./src
      args:
        - MVN_PROFILES=paymentservice,splunk
        - DPS_SERVICE_NAME=paymentservice
    environment: 
      - spring_profiles_active=cloud,splunk
      - BAMBORA_PAYMENT_ENDPOINT=https://example.com
      - BAMBORA_MERCHANT_ID=changeme
      - BAMBORA_HASHKEY=SUPERHASHKEY
      - CRC_ENDPOINT_APPROVED=http://approved
      - CRC_ENDPOINT_DECLINED=http://declined
      - CRC_ENDPOINT_ERROR=http://error
      - SPLUNK_URL=https://dps-splunk:8088
      - SPLUNK_TOKEN=${SPLUNK_TOKEN}
      - SWAGGER_UI_ENABLED=true
    ports:
      - "8081:8081"
    networks:
      - dps-net

  #############################################################################################
  ###                            FIGARO validation service                                  ###
  #############################################################################################
  fig-validation-service:
    build:
      context: ./src
      args:
        - spring_profiles_active=cloud
        - MVN_PROFILES=figvalidationservice,splunk
        - DPS_SERVICE_NAME=figvalidationservice
    environment: 
      - SWAGGER_UI_ENABLED=true
      - FIGCR_BASE_PATH=$FIGCR_BASE_PATH
    ports:
      - "8082:8081"
    networks:
      - dps-net
  
  #############################################################################################
  ###        DPS validation service (Driver Fitness Case Management Service)                ###
  #############################################################################################
  dps-validation-service:
    build:
      context: ./src
      args:
        - spring_profiles_active=cloud
        - MVN_PROFILES=dpsvalidationservice,splunk
        - DPS_SERVICE_NAME=dpsvalidationservice
    environment: 
      - SWAGGER_UI_ENABLED=true
      - DFCMS_BASE_PATH=$DFCMS_BASE_PATH
    ports:
      - "8083:8081"
    networks:
      - dps-net

  #############################################################################################
  ###                     DPS Notification Service                                          ###
  #############################################################################################
  dps-notification-service:
    build:
      context: ./src
      args:
        - MVN_PROFILES=dpsnotificationservice
        - DPS_SERVICE_NAME=dpsnotificationservice
    ports:
      - "8084:8080"
    networks:
      - dps-net
  #############################################################################################
  ###                     SPD Notification Worker                                          ###
  #############################################################################################
  dps-notification-worker:
    build:
      context: ./src
      args:
        - MVN_PROFILES=dpsnotificationworker
        - DPS_SERVICE_NAME=dpsnotificationworker
    ports:
      - "8085:8080"
    networks:
      - dps-net


  #############################################################################################
  ###                                 SPLUNK DEV BOX                                        ###
  #############################################################################################
  dps-splunk:
    image: splunk/splunk:7.3.2
    environment:
      - SPLUNK_PASSWORD=${SPLUNK_PWD}
      - SPLUNK_START_ARGS=--accept-license
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8088:8088"
      - "8089:8089"
      - "9997:9997"
    networks:
      - dps-net


volumes:
  nginx-log:

networks: 
  dps-net:
    driver: "bridge"
