
version: '3.7'
services:
  
  #############################################################################################
  ###                               DPS service API                                         ###
  #############################################################################################
  service-api:
    image: nginx:latest
    volumes:
      - ./src/service-api/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5000:80
    networks:
      - dps-net

  #############################################################################################
  ###                               DPS payment service                                     ###
  #############################################################################################
  payment-service:
    build:
      context: ./src/paymentservice
    environment: 
      - spring_profiles_active=cloud 
      - BAMBORA_PAYMENT_ENDPOINT=https://example.com
      - BAMBORA_MERCHANT_ID=changeme
      - BAMBORA_HASHKEY=SUPERHASHKEY
      - CRC_ENDPOINT_APPROVED=http://approved
      - CRC_ENDPOINT_DECLINED=http://declined
      - CRC_ENDPOINT_ERROR=http://error
    ports:
      - "8081"
    networks:
      - dps-net

networks: 
  dps-net:
    driver: "bridge"
