
version: '3.7'
services:
  
  #############################################################################################
  ###                               DPS payment service                                     ###
  #############################################################################################
  payment-service:
    build:
      context: ./src/paymentservice
    ports:
      - "5050:8081"
    networks:
      - dps-net

networks: 
  dps-net:
    driver: "bridge"
