swagger: '2.0'
info:
  title: ORDS generated API for web
  version: 1.0.0
host: localhost
basePath: "/ords/deva/figcrpords/web"
schemes:
- http
produces:
- application/json
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication.
tags:
- name: FIGVALIDATIONS
- name: Facility
paths:
  /matchingApplicants:
    get:
      operationId: matchingApplicants
      description: Locate the matching applicants
      responses:
        '200':
          description: output of the endpoint
          schema:
            type: object
            properties: {}
      parameters:
      - name: appl_alias_firstname1
        in: query
        type: string
        description: Implicit parameter
      - name: appl_alias_firstname2
        in: query
        type: string
        description: Implicit parameter
      - name: appl_alias_firstname3
        in: query
        type: string
        description: Implicit parameter
      - name: appl_alias_secondinitial1
        in: query
        type: string
        description: Implicit parameter
      - name: appl_alias_secondinitial2
        in: query
        type: string
        description: Implicit parameter
      - name: appl_alias_secondinitial3
        in: query
        type: string
        description: Implicit parameter
      - name: appl_alias_surname1
        in: query
        type: string
        description: Implicit parameter
      - name: appl_alias_surname2
        in: query
        type: string
        description: Implicit parameter
      - name: appl_alias_surname3
        in: query
        type: string
        description: Implicit parameter
      - name: appl_birthdate
        in: query
        type: string
        description: Implicit parameter
      - name: appl_birthplace
        in: query
        type: string
        description: Implicit parameter
      - name: appl_driverslicense
        in: query
        type: string
        description: Implicit parameter
      - name: appl_firstname
        in: query
        type: string
        description: Implicit parameter
      - name: appl_gender
        in: query
        type: string
        description: Implicit parameter
      - name: appl_secondinitial
        in: query
        type: string
        description: Implicit parameter
      - name: appl_surname
        in: query
        type: string
        description: Implicit parameter
  /validateApplicantForSharing:
    get:
      operationId: validateApplicantForSharing
      tags:
      - FIGVALIDATIONS
      security:
      - basicAuth: []
      description: Validate the applicant for sharing
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/validateApplicantForSharingOrdsResponse'
      parameters:
      - name: applicant_party_id
        in: query
        type: string
        description: Implicit parameter
      - name: jurisdiction_type
        in: query
        type: string
        description: Implicit parameter
  /validateApplicantPartyId:
    get:
      operationId: validateApplicantPartyId
      tags:
      - FIGVALIDATIONS
      security:
      - basicAuth: []
      description: Validate the applicant party id
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/validateApplicantPartyIdOrdsResponse'
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/errorMessage'
      parameters:
      - name: applicant_party_id
        in: query
        type: string
        description: Implicit parameter
      - name: status_code
        in: query
        type: string
        description: Implicit parameter
  /validateFacilityParty:
    get:
      tags:
      - Facility
      operationId: validateFacilityParty
      description: Validate the facility party
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/validateFacilityPartyOrdsResponse'
      parameters:
      - name: facility_party_id
        in: query
        type: string
        description: Implicit parameter
      - name: facility_subname1
        in: query
        type: string
        description: Implicit parameter
      - name: facility_subname2
        in: query
        type: string
        description: Implicit parameter
      - name: facility_subname3
        in: query
        type: string
        description: Implicit parameter
      - name: facility_subname4
        in: query
        type: string
        description: Implicit parameter
      - name: facility_subname5
        in: query
        type: string
        description: Implicit parameter
  /validateOrgApplicantService:
    get:
      operationId: validateOrgApplicantService
      tags:
      - FIGVALIDATIONS
      security:
      - basicAuth: []
      description: Validate the organization applicant service
      responses:
        '200':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/validateApplicantServiceOrdsResponse'
        '400':
          description: output of the endpoint
          schema:
            $ref: '#/definitions/errorMessage'
      parameters:
      - name: appl_party_id
        in: query
        type: string
        description: Implicit parameter
      - name: org_party_id
        in: query
        type: string
        description: Implicit parameter
      - name: status_code
        in: query
        type: string
        description: Implicit parameter
  /validateOrgDrawDownBalance:
    get:
      operationId: validateOrgDrawDownBalance
      description: Validate the organization draw down balance
      responses:
        '200':
          description: output of the endpoint
          schema:
            type: object
            properties: {}
      parameters:
      - name: jurisdiction_type
        in: query
        type: string
        description: Implicit parameter
      - name: org_party_id
        in: query
        type: string
        description: Implicit parameter
      - name: schedule_type
        in: query
        type: string
        description: Implicit parameter
      - name: status_code
        in: query
        type: string
        description: Implicit parameter
  /validateOrgParty:
    get:
      operationId: validateOrgParty
      description: Validate the organization party
      responses:
        '200':
          description: output of the endpoint
          schema:
            type: object
            properties: {}
      parameters:
      - name: org_city
        in: query
        type: string
        description: Implicit parameter
      - name: org_party_id
        in: query
        type: string
        description: Implicit parameter
      - name: org_subname1
        in: query
        type: string
        description: Implicit parameter
      - name: org_subname2
        in: query
        type: string
        description: Implicit parameter
      - name: org_subname3
        in: query
        type: string
        description: Implicit parameter
      - name: org_subname4
        in: query
        type: string
        description: Implicit parameter
      - name: org_subname5
        in: query
        type: string
        description: Implicit parameter
  /health:
    get:
      operationId: health
      description: Dummy endpoint to check that API calls are working
      responses:
        '200':
          description: output of the endpoint
          schema:
            type: object
            properties: {}
definitions:
  validateApplicantPartyIdOrdsResponse:
    type: object
    required:
    - surname
    - first_name
    - second_name
    - birth_date
    - drivers_license
    - birth_place
    - gender
    - status_code
    - status_message
    properties:
      surname:
        type: string
      first_name:
        type: string
      second_name:
        type: string
      birth_date:
        type: string
      drivers_license:
        type: string
      birth_place:
        type: string
      gender:
        type: string
      status_code:
        type: string
      status_message:
        type: string
  validateApplicantForSharingOrdsResponse:
    type: object
    required:
    - validation_result
    - status_code
    - status_message
    properties:
      validation_result:
        type: string
      status_code:
        type: string
      status_message:
        type: string
  validateFacilityPartyOrdsResponse:
    type: object
    required:
    - validation_result
    - found_facility_party_id
    - found_facility_name
    - status_code
    - status_message
    properties:
      validation_result:
        type: string
      found_facility_party_id:
        type: string
      found_facility_name:
        type: string
      status_code:
        type: string
      status_message:
        type: string
  errorMessage:
    type: object
    required:
    - status_code
    - status_message
    properties:
      status_code:
        type: string
      status_message:
        type: string
  validateApplicantServiceOrdsResponse:
    type: object
    required:
    - validation_result
    - status_code
    - status_message
    properties:
      validation_result:
        type: string
      status_code:
        type: string
      status_message:
        type: string   
