---
kind: Template
apiVersion: v1
metadata:
  name: dps-validation-service-build
  annotations:
    openshift.io/display-name: "DPS Validation Service Build"
    description: The DPS Validation Service builder
    tags: java
    template.openshift.io/provider-display-name: BCGov
    template.openshift.io/documentation-url: https://github.com/bcgov/jag-dps/

parameters:
  - name: NAME
    displayName: Name
    description: A prefix appended to all objects
    required: true
  - name: SOURCE_CONTEXT_DIR
    required: true
  - name: SOURCE_REPOSITORY_URL
    required: true
  - name: SOURCE_REPOSITORY_REF
    required: true
  - name: OC_PREFIX
    required: true
  - name: OC_APP
    required: true
  - name: VERSION
    required: true
  # TODO Value needs to change at some point
  - name: DFCMS_BASE_PATH
    required: true
    value: ""
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: '${NAME}${SUFFIX}'
      labels:
        shared: 'true'
      annotations: {}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: '${NAME}'
          annotations: null
          from:
            kind: ImageStreamTag
            name: 'dps-validation-service:latest'
            namespace: openshift
          generation: 1
          importPolicy: {}
          referencePolicy:
            type: Local
