---
kind: Template
apiVersion: v1
metadata:
  name: dps-payment-service-build
  annotations:
    openshift.io/display-name: "DPS Payment Service Build"
    description: The DPS Payment Service builder
    tags: java
    template.openshift.io/provider-display-name: BCGov
    template.openshift.io/documentation-url: https://github.com/bcgov/jag-dps/

parameters:
  - name: APP_NAME
    displayName: Name
    description: A prefix appended to all objects
    required: true
  - name: SOURCE_CONTEXT_DIR
    required: true
  - name: GIT_URL
    required: true
  - name: REPO_REF
    required: true
  - name: PROJECT_PREFIX
    required: true
  - name: APP_NAME
    required: true
  - name: SPRING_PROFILES_ACTIVE
    required: true
  - name: BAMBORA_PAYMENT_ENDPOINT
    required: true
  - name: BAMBORA_MERCHANT_ID
    required: true
  - name: BAMBORA_HASHKEY
    required: true
  - name: CRC_ENDPOINT_APPROVED
    required: true
  - name: CRC_ENDPOINT_DECLINED
    required: true
  - name: SPLUNK_URL
    required: true
  - name: SPLUNK_TOKEN
    required: true
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: '${NAME}${SUFFIX}'
      labels:
        shared: 'true'
      annotations: {}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: '${APP_NAME}'
          annotations: null
          from:
            kind: ImageStreamTag
            name: 'dps-payment-service:latest'
            namespace: openshift
          generation: 1
          importPolicy: {}
          referencePolicy:
            type: Local