---
kind: Template
apiVersion: v1
metadata:
  name: dps-payment-service-build
  annotations:
    openshift.io/display-name: "DPS Payment Service Build"
    description: The DPS Payment Service builder
    tags: java
    template.openshift.io/provider-display-name: BCGov
    template.openshift.io/documentation-url: https://github.com/bcgov/jag-dps/
parameters:
  - name: NAME
    displayName: Name
    description: A prefix appended to all objects
    required: true
  - name: SOURCE_CONTEXT_DIR
    required: true
  - name: SOURCE_REPOSITORY_URL
    required: true
  - name: SOURCE_REPOSITORY_REF
    required: true
  - name: OC_PREFIX
    required: true
  - name: OC_APP
    required: true
  - name: VERSION
    required: true
  - name: SPRING_PROFILES_ACTIVE
    required: true
    value: "cloud,splunk"
  - name: BAMBORA_PAYMENT_ENDPOINT
    required: true
    value: ""
  - name: BAMBORA_MERCHANT_ID
    required: true
    value: ""
  - name: BAMBORA_HASHKEY_ID
    required: true
    value: ""
  - name: CRC_ENDPOINT_APPROVED
    required: true
    value: ""
  - name: CRC_ENDPOINT_DECLINED
    required: true
    value: ""
  - name: SPLUNK_URL
    required: true
    value: ""
  - name: SPLUNK_TOKEN
    required: true 
    value: ""
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: '${NAME}${SUFFIX}'
      labels:
        shared: 'true'
      annotations: {}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: '${NAME}'
          annotations: null
          from:
            kind: ImageStreamTag
            name: 'dps-payment-service:latest'
            namespace: openshift
          generation: 1
          importPolicy: {}
          referencePolicy:
            type: Local