apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"figaro-validation-service"},"name":"figaro-validation-service","namespace":"pjztlm-dev"},"spec":{"replicas":2,"selector":{"io.kompose.service":"figaro-validation-service"},"strategy":{"resources":{}},"template":{"metadata":{"creationTimestamp":null,"labels":{"io.kompose.service":"figaro-validation-service"}},"spec":{"containers":[{"image":"","name":"figaro-validation-service","ports":[{"containerPort":8080}],"resources":{}}],"restartPolicy":"Always"}},"test":false,"triggers":[{"type":"ConfigChange"},{"imageChangeParams":{"automatic":true,"containerNames":["figaro-validation-service"],"from":{"kind":"ImageStreamTag","name":"figaro-validation-service:dev","namespace":"pjztlm-tools"}},"type":"ImageChange"}]},"status":{}}
  creationTimestamp: 
  generation: 28
  labels:
    app: figaro-validation-service
  name: figaro-validation-service
  namespace: pjztlm-dev
  resourceVersion: '1654117080'
  selfLink: >-
    /apis/apps.openshift.io/v1/namespaces/pjztlm-{DEV/TEST/PROD}/deploymentconfigs/figaro-validation-service
  uid: 53407d15-5da1-11ea-8a92-0050568379a2
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    io.kompose.service: figaro-validation-service
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: figaro-validation-service
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: spring-profiles-active
            - secretRef:
                name: figaro-api-secrets
            - secretRef:
                name: splunk-config
          image: >-
            docker-registry.default.svc:5000/pjztlm-tools/figaro-validation-service@sha256:00553211b887d1bdb203aa8cbb399f63b8e6c400c6470542df7c724320cecdca
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /figvalidationservice/actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: figaro-validation-service
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /figvalidationservice/actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 80
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources: {}
          terminationMessagePath: /{DEV/TEST/PROD}/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - figaro-validation-service
        from:
          kind: ImageStreamTag
          name: 'figaro-validation-service:{DEV/TEST/PROD}'
          namespace: pjztlm-tools
        lastTriggeredImage: >-
          docker-registry.default.svc:5000/pjztlm-tools/figaro-validation-service@sha256:00553211b887d1bdb203aa8cbb399f63b8e6c400c6470542df7c724320cecdca
      type: ImageChange
status:
  availableReplicas: 2
  conditions:
    - lastTransitionTime: 
      lastUpdateTime: 
      message: >-
        replication controller "figaro-validation-service-1" successfully
        rolled out
      reason: NewReplicationControllerAvailable
      status: 'True'
      type: Progressing
    - lastTransitionTime: 
      lastUpdateTime: 
      message: Deployment config has minimum availability.
      status: 'True'
      type: Available
  details:
    causes:
      - imageTrigger:
          from:
            kind: DockerImage
            name: >-
              docker-registry.default.svc:5000/pjztlm-tools/figaro-validation-service@sha256:00553211b887d1bdb203aa8cbb399f63b8e6c400c6470542df7c724320cecdca
        type: ImageChange
    message: image change
  latestVersion: 1
  observedGeneration: 28
  readyReplicas: 2
  replicas: 2
  unavailableReplicas: 0
  updatedReplicas: 2
