apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=deploy-config --build-repo=https://github.com/bcgov/jag-dps
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: dps-splunk
  name: dps-splunk
spec:
  replicas: 1
  selector:
    io.kompose.service: dps-splunk
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/dps-net: "true"
        io.kompose.service: dps-splunk
    spec:
      containers:
      - env:
        - name: SPLUNK_PASSWORD
        - name: SPLUNK_START_ARGS
          value: --accept-license
        image: ' '
        name: dps-splunk
        ports:
        - containerPort: 8000
        - containerPort: 8001
        - containerPort: 8088
        - containerPort: 8089
        - containerPort: 9997
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - dps-splunk
      from:
        kind: ImageStreamTag
        name: dps-splunk:7.3.2
    type: ImageChange
status: {}
