apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=deploy-config --build-repo=https://github.com/bcgov/jag-dps
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: dps-splunk
  name: dps-splunk
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  - name: "8001"
    port: 8001
    targetPort: 8001
  - name: "8088"
    port: 8088
    targetPort: 8088
  - name: "8089"
    port: 8089
    targetPort: 8089
  - name: "9997"
    port: 9997
    targetPort: 9997
  selector:
    io.kompose.service: dps-splunk
status:
  loadBalancer: {}
