apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: dps-splunk
  name: dps-splunk
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: splunk/splunk:7.3.2
    generation: null
    importPolicy: {}
    name: 7.3.2
status:
  dockerImageRepository: ""
