apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: fig-validation-service
  name: fig-validation-service
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: fig-validation-service
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
