apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=deploy-config --build-repo=https://github.com/bcgov/jag-dps
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: fig-validation-service
  name: fig-validation-service
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8081
  selector:
    io.kompose.service: fig-validation-service
status:
  loadBalancer: {}
