apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=deploy-config --build-repo=https://github.com/bcgov/jag-dps
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: fig-validation-service
  name: fig-validation-service
spec:
  replicas: 1
  selector:
    io.kompose.service: fig-validation-service
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/dps-net: "true"
        io.kompose.service: fig-validation-service
    spec:
      containers:
      - env:
        - name: SWAGGER_UI_ENABLED
          value: "true"
        image: ' '
        name: fig-validation-service
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - fig-validation-service
      from:
        kind: ImageStreamTag
        name: fig-validation-service:latest
    type: ImageChange
status: {}
