apiVersion: secops.pathfinder.gov.bc.ca/v1alpha1
kind: NetworkSecurityPolicy
metadata:
  name: intra-namespace-comms
  labels:
    app: tools
spec:
  description: |
    allow all pods in the namespace to talk amongst
    themselves
  source:
    - - $namespace=pjztlm-tools
  destination:
    - - $namespace=pjztlm-dev
    - - $namespace=pjztlm-test
    - - $namespace=pjztlm-prod
    - - $namespace=pjztlm-tools