apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=deploy-config --build-repo=https://github.com/bcgov/jag-dps
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: payment-service
  name: payment-service
spec:
  replicas: 1
  selector:
    io.kompose.service: payment-service
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/dps-net: "true"
        io.kompose.service: payment-service
    spec:
      containers:
      - env:
        - name: BAMBORA_HASHKEY
          value: SUPERHASHKEY
        - name: BAMBORA_MERCHANT_ID
          value: changeme
        - name: BAMBORA_PAYMENT_ENDPOINT
          value: https://example.com
        - name: CRC_ENDPOINT_APPROVED
          value: http://approved
        - name: CRC_ENDPOINT_DECLINED
          value: http://declined
        - name: CRC_ENDPOINT_ERROR
          value: http://error
        - name: SPLUNK_TOKEN
        - name: SPLUNK_URL
          value: https://dps-splunk:8088
        - name: SWAGGER_UI_ENABLED
          value: "true"
        - name: spring_profiles_active
          value: cloud,splunk
        image: ' '
        name: payment-service
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - payment-service
      from:
        kind: ImageStreamTag
        name: payment-service:latest
    type: ImageChange
status: {}
