apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: service-api
  name: service-api
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: nginx:latest
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
