apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=deploy-config --build-repo=https://github.com/bcgov/jag-dps
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: service-api-universalforwarder
  name: service-api-universalforwarder
spec:
  ports:
  - name: "8089"
    port: 8089
    targetPort: 8089
  - name: "9997"
    port: 9997
    targetPort: 9997
  selector:
    io.kompose.service: service-api-universalforwarder
status:
  loadBalancer: {}
