apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: service-api-universalforwarder
  name: service-api-universalforwarder
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: splunk/universalforwarder:7.3.2
    generation: null
    importPolicy: {}
    name: 7.3.2
status:
  dockerImageRepository: ""
