apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=deploy-config --build-repo=https://github.com/bcgov/jag-dps
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: service-api
  name: service-api
spec:
  replicas: 1
  selector:
    io.kompose.service: service-api
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/dps-net: "true"
        io.kompose.service: service-api
    spec:
      containers:
      - image: ' '
        name: service-api
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          name: service-api-claim0
        - mountPath: /var/log/nginx
          name: service-api-claim1
      restartPolicy: Always
      volumes:
      - name: service-api-claim0
        persistentVolumeClaim:
          claimName: service-api-claim0
      - name: service-api-claim1
        persistentVolumeClaim:
          claimName: service-api-claim1
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - service-api
      from:
        kind: ImageStreamTag
        name: service-api:latest
    type: ImageChange
status: {}
