apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=deploy-config --build-repo=https://github.com/bcgov/jag-dps
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: service-api-universalforwarder
  name: service-api-universalforwarder
spec:
  replicas: 1
  selector:
    io.kompose.service: service-api-universalforwarder
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.network/dps-net: "true"
        io.kompose.service: service-api-universalforwarder
    spec:
      containers:
      - env:
        - name: SPLUNK_PASSWORD
        - name: SPLUNK_START_ARGS
          value: --accept-license
        image: ' '
        name: service-api-universalforwarder
        ports:
        - containerPort: 8089
        - containerPort: 9997
        resources: {}
        volumeMounts:
        - mountPath: /opt/splunkforwarder/etc/system/local/inputs.conf
          name: service-api-universalforwarder-claim0
        - mountPath: /opt/splunkforwarder/etc/system/local/outputs.conf
          name: service-api-universalforwarder-claim1
        - mountPath: /var/log/nginx
          name: service-api-universalforwarder-claim2
      restartPolicy: Always
      volumes:
      - name: service-api-universalforwarder-claim0
        persistentVolumeClaim:
          claimName: service-api-universalforwarder-claim0
      - name: service-api-universalforwarder-claim1
        persistentVolumeClaim:
          claimName: service-api-universalforwarder-claim1
      - name: service-api-universalforwarder-claim2
        persistentVolumeClaim:
          claimName: service-api-universalforwarder-claim2
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - service-api-universalforwarder
      from:
        kind: ImageStreamTag
        name: service-api-universalforwarder:7.3.2
    type: ImageChange
status: {}
