version: '3.7'
services:

  #############################################################################################
  ###                            FIGARO validation service                                  ###
  #############################################################################################
  fig-validation-service:
    build:
      context: ./src
      args:
        - spring_profiles_active=cloud
        - MVN_PROFILES=figvalidationservice,splunk
        - DPS_SERVICE_NAME=figvalidationservice
    environment: 
      - SWAGGER_UI_ENABLED=true
    ports:
      - "8082:8081"
    networks:
      - dps-net
