name: Static Code Analysis

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Sonar Scan
      run: mvn clean verify sonar:sonar --file src/pom.xml -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_LOGIN }} -Dsonar.language=java -Dsonar.jacoco.reportPath=target/aggregate.exec
